# Colors variables {{{
red="\e[31m"
green="\e[32m"
yellow="\e[33m"
blue="\e[34m"
magenta="\e[35m"
cyan="\e[36m"
back_red="\e[41m"
back_green="\e[42m"
back_yellow="\e[43m"
back_blue="\e[44m"
back_magenta="\e[45m"
back_cyan="\e[46m"
reset="\e[0m" # }}}

# Newt templates {{{
NEWT_COLORS_0='
    root=,blue
'
NEWT_COLORS_1='
    root=,blue
    checkbox=,blue
    entry=,blue
    label=blue,
    actlistbox=,blue
    helpline=,blue
    roottext=,blue
    emptyscale=blue
    disabledentry=blue,
'
NEWT_COLORS_2='
    root=green,black
    border=green,black
    title=green,black
    roottext=white,black
    window=green,black
    textbox=white,black
    button=black,green
    compactbutton=white,black
    listbox=white,black
    actlistbox=black,white
    actsellistbox=black,green
    checkbox=green,black
    actcheckbox=black,green
'
NEWT_COLORS_3='
    root=white,black
    border=black,lightgray
    window=lightgray,lightgray
    shadow=black,gray
    title=black,lightgray
    button=black,cyan
    actbutton=white,cyan
    compactbutton=black,lightgray
    checkbox=black,lightgray
    actcheckbox=lightgray,cyan
    entry=black,lightgray
    disentry=gray,lightgray
    label=black,lightgray
    listbox=black,lightgray
    actlistbox=black,cyan
    sellistbox=lightgray,black
    actsellistbox=lightgray,black
    textbox=black,lightgray
    acttextbox=black,cyan
    emptyscale=,gray
    fullscale=,cyan
    helpline=white,black
    roottext=lightgrey,black
'

NEWT_COLORS_4='
    root=,blue
    window=,black
    shadow=,blue
    border=blue,black
    title=blue,black
    textbox=blue,black
    radiolist=black,black
    label=black,blue
    checkbox=black,blue
    compactbutton=black,blue
    button=black,red
'

NEWT_COLORS_5='
    root=white,gray
    window=white,lightgray
    border=black,lightgray
    shadow=white,black
    button=black,green
    actbutton=black,red
    compactbutton=black,
    title=black,
    roottext=black,magenta
    textbox=black,lightgray
    acttextbox=gray,white
    entry=lightgray,gray
    disentry=gray,lightgray
    checkbox=black,lightgray
    actcheckbox=black,green
    emptyscale=,black
    fullscale=,red
    listbox=black,lightgray
    actlistbox=lightgray,gray
    actsellistbox=black,green
' 
# }}}
